jobs:
    - job: plan
      steps:
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/parent/${{ parameters.env }}'
           backendServiceArm: 'hclservicrc'
           backendAzureRmStorageAccountName: 'hclsa456233'
           backendAzureRmContainerName: 'tfstate'
           backendAzureRmKey: '$ {{  parameters.env }}.terraform.tfstate'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: '$(System.DefaultWorkingDirectory)/parent/${{ parameters.env }}'
           environmentServiceNameAzureRM: 'hclservicrc'

           